# Use the official nginx image as the base image
FROM nginx:1.25-alpine
# Remove default nginx configuration
RUN rm -f /etc/nginx/conf.d/default.conf
# Copy custom nginx configuration and index.html to the appropriate locations
#COPY ./nginx.conf /etc/nginx/conf.d/default.conf
COPY ./nginx.conf.template /etc/nginx/templates/default.conf.template
COPY ./index.html /usr/share/nginx/html/index.html
# Expose port 80 for the web server
EXPOSE 80
# Start nginx in the foreground
#CMD ["nginx", "-g", "daemon off;"]
CMD ["/bin/sh", "-c", "envsubst '${AUTH_SVC_HOST},${AUTH_SVC_PORT},${NOTES_SVC_HOST},${NOTES_SVC_PORT}' < /etc/nginx/templates/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"]



