apiVersion: v1
kind: Service
metadata:
  name: notes-svc
  namespace: notes
spec:
  selector:
    app: notes-app
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
  type: ClusterIP
