# Postgres credentials for notes namespace
apiVersion: v1
kind: Secret
metadata:
  name: pg-credentials
  namespace: notes
type: Opaque
stringData:
  username: postgres
  password: postgres123
---
# Azurite connection string for local minikube
# On AKS replace this value with your real Azure Blob Storage connection string
apiVersion: v1
kind: Secret
metadata:
  name: blob-credentials
  namespace: notes
type: Opaque
stringData:
  connection-string: "DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurite.storage.svc.cluster.local:10000/devstoreaccount1;"